server:
  port: 8081
#  servlet:
#    context-path: /one-piece

spring:
  datasource:
    druid:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/one-piece
        username: root
        password: root

        #配置初始化大小、最小、最大  注意 如果这里这三个配置大于数据库最大限制,会抛出异常
        initial-size: 5
        min-idle: 10
        max-active: 20
        #配置获取连接等待超时的时间
        max-wait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        #检测连接是否有效的sql
        validation-query: SELECT 'x'
        #这参数找不到参考意义
        validation-query-timeout: 10
        #申请连接时执行validationQuery检测连接是否有效
        test-on-borrow: true
        #归还连接时执行validationQuery检测连接是否有效
        test-on-return: false
        #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery
        test-while-idle: true
        #打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        #配置监控统计拦截的filters
        filters: stat
        tomcat:
          connection-properties: useSSL=false;serverTimezone=UTC;characterEncoding=utf8
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 20000

mybatis-plus:
  mapper-locations: classpath*:com/you/mapper/*Mapper.xml     # 存放sql语句的xml文件目录
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 放开则开启SQL打印
    map-underscore-to-camel-case: true   # 开启驼峰法则
  type-aliases-package: com.you.entity   # 实体类包路径

jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

# SSH通道连接服务器配置信息
ssh:
  user: root          # 服务器登录名
  password: Yyfyp@@123    # 登陆密码
  host: 58.67.221.164     # 服务器公网IP
  port: 22              # 跳板机ssh开放的接口
  remote_host: localhost      # 要访问的mysql所在的host
  mysql_remote_port: 3306     # 服务器上数据库端口号
  mysql_local_port: 3307      # Mysql 本地的端口
  redis_local_port: 6379      # redis 本地的端口
  redis_remote_port: 6379     # 服务器上redis端口号